server:
  context-path: /sell
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://sell.com/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true